/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CarIcons {
  CarIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData convertible = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupe = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossover = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hatchback = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minivan = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sedan = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sport = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suv = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
